name: CI_Pipeline

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show status
        run: git status

      - name: List files
        run: ls -la

      - name: Check for config file
        run: |
          if [ -f "config/app.conf" ]; then
            echo "✅ config/app.conf найден"
          else
            echo "❌ config/app.conf не найден"
            exit 1
          fi
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Pages
        uses: actions/configure-pages@v3
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs  # Путь к твоим статическим файлам
  
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
